### ISSUE TITLE
Final Jeopardy

### ISSUE THREAD

**Issue by leskat47** [leskat47/jeopardy-angular#2]
-Put a Final Jeopardy question on the screen. 
-Title Screen, Question & Answer
-Betting $ (must be equal or less than player.score)
-Give us a winner for the game

Nice to have:
-Final Jeopardy title screen comes up when all questions have been completed. On click, it shows the first question, and then click again for answer.

**Comment by leskat47** [comment]
Final jeopardy button appears when all questions have been completed.

The button brings up the question, but betting still isn't set up. It should probably be inserted as an intermediate step, maybe a modal before the question modal.

**Comment by chatasweetie** [comment]
Nice! I've started working on the betting :)

**Comment by chatasweetie** [comment]
Got the custom betting to work and subtract/add to score, then assigned a winner and show a modal for the announcing the winner. Found a weird bug, not sure why, but at time it doesn't show the winner modal. This needs to be debugged
![screen shot 2016-07-10 at 9 11 02 pm](https://cloud.githubusercontent.com/assets/12740421/16719736/f0d93cba-46e2-11e6-9589-eaf8e0b78472.png)

![screen shot 2016-07-10 at 9 11 13 pm](https://cloud.githubusercontent.com/assets/12740421/16719741/fdabee1a-46e2-11e6-839b-1b00e45283ef.png)

![screen shot 2016-07-10 at 9 11 19 pm](https://cloud.githubusercontent.com/assets/12740421/16719742/ff89d4a4-46e2-11e6-9304-d0876639eddc.png)

**Comment by leskat47** [comment]
Love the screenshots. Couldn't replicate the bug.
